- name: play level variables
  hosts: web
  connection: local
  
  tasks:
    - name: print variables
      vars:
        Course: Ansible
      ansible.builtin.debug:
        msg: "Course name is {{Course}}"